version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  build-and-deploy: &build-and-deploy
    docker:
      - image: cimg/node:16.13

    steps:
      - checkout

      - node/install-packages:
          pkg-manager: yarn

      ## only install s3deployer-cli (call without yarn)
      # - run:
      #     name: Install s3deployer-cli
      #     command: npm install --prefix=$HOME/.local --global @whatskit/s3deployer-cli

      # Run tests/eslint
      # - run: npm run task:eslint

      - run: yarn run build

      # RUN DEPLOY SCRIPT
      #  add version and variables to header
      #  create targeted invalidations
      - run:
          name: Deploy to S3
          command: yarn s3deployer-cli deploy

      - run:
          name: Slack message on success
          command: yarn slack-notify-cli --messageType success

      - run:
          name: Slack message on fail
          command: yarn slack-notify-cli --messageType failure
          when: on_fail

  myapp-dev:
    <<: *build-and-deploy
    environment:
      STAGE: myapp-dev
      # add variables to config.yaml
      # add secrets to circleci environment

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - myapp-dev:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: myapp-dev
